drivers: input: focaltech: X01BD: Drop cpu boost
• This invokes a build error now due to implicit function as we have dropped CPU_BOOST config

	../drivers/input/fingerprint/focaltech_X01BD/ff_ctl.c:148:9: error: implicit declaration of function 'sched_set_boost' [-Werror,-Wimplicit-function-declaration]
	                ret = sched_set_boost(0);
	                      ^
	../drivers/input/fingerprint/focaltech_X01BD/ff_ctl.c:161:9: error: implicit declaration of function 'sched_set_boost' [-Werror,-Wimplicit-function-declaration]
	                ret = sched_set_boost(1);
	                      ^
	2 errors generated.

• Previously it used to complain in logs that it never worked as we arent HMP anymore.
• Also why the heck do we need cpu boost in a fp driver? Why Asus?

Change-Id: Id23b1d464846c9099ca49ded0640b13cf605ec24
Signed-off-by: Kunmun <kunmun.devroms@gmail.com>